// This file is autogenerated. Changes will be overwritten.
#include "DMHXEJ42XS/moc_example_tabs.cpp"
#include "DMHXEJ42XS/moc_kernel_runner.cpp"
#include "DMHXEJ42XS/moc_mainwindow.cpp"
#include "DMHXEJ42XS/moc_performance_widget.cpp"
#include "DMHXEJ42XS/moc_result_viewer.cpp"
#include "DMHXEJ42XS/moc_test_runner.cpp"
